import type { ColConfigMap, TileDefinition } from "@/types";

export const COL_CONFIG: ColConfigMap = {
  action: {
    label: "Action required",
    accent: "border-orange-700",
    bg: "bg-orange-50",
    border: "border-orange-300",
    dot: "bg-orange-600",
    pillBg: "bg-orange-50",
    pillText: "text-orange-800",
    pillBorder: "border-orange-200",
  },
  overdue: {
    label: "Overdue",
    accent: "border-red-700",
    bg: "bg-red-50",
    border: "border-red-300",
    dot: "bg-red-600",
    pillBg: "bg-red-50",
    pillText: "text-red-800",
    pillBorder: "border-red-200",
  },
  sub: {
    label: "Subscriptions",
    accent: "border-gray-400",
    bg: "bg-gray-50",
    border: "border-gray-300",
    dot: "bg-gray-400",
    pillBg: "bg-gray-100",
    pillText: "text-gray-700",
    pillBorder: "border-gray-200",
  },
  other: {
    label: "FYI",
    accent: "border-violet-700",
    bg: "bg-violet-50",
    border: "border-violet-300",
    dot: "bg-violet-500",
    pillBg: "bg-violet-50",
    pillText: "text-violet-800",
    pillBorder: "border-violet-200",
  },
  invoice: {
    label: "Invoices",
    accent: "border-amber-500",
    bg: "bg-amber-50",
    border: "border-amber-300",
    dot: "bg-amber-500",
    pillBg: "bg-amber-50",
    pillText: "text-amber-800",
    pillBorder: "border-amber-200",
  },
};

// Dashboard tile definitions — each tile aggregates one or more columns
export const TILE_DEFINITIONS: TileDefinition[] = [
  {
    id: "action",
    label: "Action Required",
    subtitle: "Needs your reply or decision",
    cols: ["action", "overdue"],
    accentTop: "border-t-red-500",
    countColor: "text-red-500",
    icon: "⚡",
  },
  {
    id: "sub",
    label: "Subscriptions",
    subtitle: "Newsletters & promotions",
    cols: ["sub"],
    accentTop: "border-t-blue-500",
    countColor: "text-blue-500",
    icon: "📨",
  },
  {
    id: "invoice",
    label: "Invoices",
    subtitle: "Bills & payment requests",
    cols: ["invoice"],
    accentTop: "border-t-amber-500",
    countColor: "text-amber-500",
    icon: "🧾",
  },
  {
    id: "other",
    label: "FYI",
    subtitle: "Informational updates",
    cols: ["other"],
    accentTop: "border-t-teal-500",
    countColor: "text-teal-500",
    icon: "💡",
  },
];
