import type { Card } from "@/types";

export const PLACEHOLDER_CARDS: Card[] = [
  // ── Action required ──────────────────────────────────────────────────────
  {
    id: "placeholder-1",
    col: "action",
    sender: "Sarah Chen",
    senderType: "client",
    time: "2h ago",
    task: "Send updated contract before EOD — she needs sign-off for legal",
    reason: "Money/contract + \"EOD\" deadline detected",
    deadline: "Today EOD",
    reply: "Hi Sarah, sending the updated contract shortly. Will have it over before end of day.",
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-2",
    col: "action",
    sender: "Alex (CEO)",
    senderType: "boss",
    time: "4h ago",
    task: "Loop in Maria and schedule time next week to review Q3 deck",
    reason: "Sender is CEO — auto-elevated priority",
    deadline: "Next week",
    reply: "On it — looping Maria now and will share a few calendar slots shortly.",
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-3",
    col: "action",
    sender: "Jorge (Client)",
    senderType: "client",
    time: "Yesterday",
    task: "Approve revised pricing sheet — he's waiting to send to procurement",
    reason: "You're blocking a client's next step",
    deadline: null,
    reply: "Approved — pricing sheet looks good, go ahead and send to procurement.",
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  // ── Overdue ──────────────────────────────────────────────────────────────
  {
    id: "placeholder-4",
    col: "overdue",
    sender: "Maria",
    senderType: "colleague",
    time: "3 days ago",
    task: "Send the onboarding doc she asked for last Tuesday",
    reason: "Follow-up email — original request 5 days old, no reply sent",
    deadline: null,
    reply: "Sorry for the delay — attaching the onboarding doc now.",
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-5",
    col: "overdue",
    sender: "Rachel (Events)",
    senderType: "colleague",
    time: "5 days ago",
    task: "Confirm venue details for Thursday — deadline was Monday",
    reason: "Deadline \"Monday\" has passed, no confirmation sent",
    deadline: null,
    reply: "Confirming now — apologies for the late response on this.",
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // ── Subscriptions ─────────────────────────────────────────────────────────
  {
    id: "placeholder-6",
    col: "sub",
    sender: "Product Hunt",
    senderType: "auto",
    time: "This morning",
    task: "Today's top products digest",
    reason: "Newsletter — no reply or action needed",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-7",
    col: "sub",
    sender: "GitHub",
    senderType: "auto",
    time: "Yesterday",
    task: "Your weekly activity summary — 3 PRs merged, 12 comments",
    reason: "Automated digest — no action needed",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-8",
    col: "sub",
    sender: "LinkedIn",
    senderType: "auto",
    time: "2 days ago",
    task: "You have 5 new connection requests and 2 messages",
    reason: "Social platform notification — no urgent action",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // ── Invoices ──────────────────────────────────────────────────────────────
  {
    id: "placeholder-9",
    col: "invoice",
    sender: "Stripe",
    senderType: "auto",
    time: "1h ago",
    task: "Monthly subscription — $49 charged to card ending 4242",
    reason: "Automated payment receipt — no action needed",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-10",
    col: "invoice",
    sender: "AWS",
    senderType: "auto",
    time: "3 days ago",
    task: "AWS bill for April — $312.40 due June 1st",
    reason: "Cloud infrastructure invoice — payment required",
    deadline: "June 1st",
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-11",
    col: "invoice",
    sender: "Figma",
    senderType: "auto",
    time: "5 days ago",
    task: "Figma Professional plan — $144/yr renewal processed",
    reason: "Annual subscription receipt — no action required",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // ── FYI / Other ───────────────────────────────────────────────────────────
  {
    id: "placeholder-12",
    col: "other",
    sender: "Dave (Design)",
    senderType: "colleague",
    time: "3h ago",
    task: "FYI — brand refresh deck shared for your awareness",
    reason: "Informational only, no reply or task expected",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-13",
    col: "other",
    sender: "HR Team",
    senderType: "auto",
    time: "Yesterday",
    task: "Company all-hands recording is now available",
    reason: "Notification email, no action required",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "placeholder-14",
    col: "other",
    sender: "Anthropic",
    senderType: "auto",
    time: "2 days ago",
    task: "Claude 3.5 Sonnet is now available — new capabilities overview",
    reason: "Product update announcement — informational",
    deadline: null,
    reply: null,
    archived: false,
    gmailMsgId: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
